namespace DotnetBatchInjection.SourceGenerator
{
    internal static class Constants
    {
        // GeneratorHelpers constants
        public const string Header = "// <auto-generated/>";
        public const string UsingStatements = """
            using Microsoft.Extensions.DependencyInjection;
            using Microsoft.Extensions.Configuration;
            """;
        public const string Namespace = "Microsoft.Extensions.DependencyInjection";
        public const string ExtensionClassTemplate = """
            {0}

            {1}

            namespace {2}
            {{
                public static partial class {3}
                {{
                    public static IServiceCollection {4}(this IServiceCollection services{5})
                    {{
                        {6}
                        return services;
                    }}
                }}
            }}
            """;

        // ServiceRegistrationGenerator constants
        public const string ServiceExtensionClassName = "DependencyInjectionExtensions";
        public const string ServiceExtensionMethodName = "RegisterServices";
        public const string ServiceRegistrationFileName = "ServiceRegistrationExtensions.g.cs";

        // ConfigRegistrationGenerator constants
        public const string ConfigExtensionClassName = "DependencyInjectionExtensions";
        public const string ConfigExtensionMethodName = "RegisterConfigs";
        public const string ConfigRegistrationFileName = "ConfigRegistrationExtensions.g.cs";
        public const string ConfigNullCheck = "            if (configuration == null) return services;";
    }
}